### PR TITLE
fix: resolve type errors after Vue 3 upgrade

### PR DESCRIPTION
**Pull request by amandaejohnston**
Resolves errors that appear when manually building the app. These weren't caught before because running `ionic serve` or `npm run dev` skips the build step, and we don't have any CI checking for it either.

### CODE REVIEW

**Comment by amandaejohnston** [comment]
Created a ticket to fix up the CI here and in the React conference app: https://ionic-cloud.atlassian.net/browse/FW-5883

**Comment by mapsandapps** [comment]
It looks like there's one more thing that needs to be changed:

in SpeakerDetail.vue, `return store.state.speakers.find` needs to change to `return store.state.speakers.speakers.find`

After I make that change, it seems like everything builds successfully.

**Comment by amandaejohnston** [comment]
Good catch 👀

**Review by mapsandapps — APPROVED** [review]
it's working for me! thanks for finding & fixing this!

**Comment by amandaejohnston** [comment]
Thanks to @sean-perkins for doing most of the work 😄

**Pull request merged**
